remote_theme: jekyll/minima
author:
  name: luabagg
  email: luanbaggio0@gmail.com
title: Learning Data Science UFSM
description: >
  ğŸ‘¨â€ğŸ’» Website destinado a conter os conteÃºdos de apoio das aulas de CiÃªncia de Dados da UFSM.
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
 skin: auto
