remote_theme: jekyll/minima
author:
  name: luabagg
  email: luanbaggio0@gmail.com
github_username: luabagg
title: Learning Data Science UFSM
description: >
  ğŸ‘¨â€ğŸ’» Website destinado a listar os conteÃºdos de apoio das aulas de CiÃªncia de Dados da UFSM.
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: auto
  social:
    - { platform: github }